version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: reisestotte-db
    restart: unless-stopped
    environment:
      # Leser verdier fra .env-filen i rotmappen
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: reisestotte-backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Bruker variablene fra .env til å koble til databasen
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build: ./frontend
    container_name: reisestotte-frontend
    restart: on-failure
    ports:
      - "3000:80"

volumes:
  db_data: